#!/bin/sh
cat << 'EOF' > /usr/lib/wireguard/wps_button.sh
#!/bin/sh

STATE_FILE="/tmp/wireguard_state"
LOG_FILE="/tmp/wireguard_log"

log_message() {
    echo "$(date): $1" >> $LOG_FILE
}

if [ ! -f $STATE_FILE ]; then
    echo "stopped" > $STATE_FILE
fi

STATE=$(cat $STATE_FILE)

log_message "Estado actual: $STATE"

case "$STATE" in
    "stopped")
        log_message "Iniciando Wireguard con perfil Config"
        /bin/sh /usr/lib/wireguard/startvpn.sh Config
        if [ $? -eq 0 ]; then
            echo "Config" > $STATE_FILE
            log_message "Wireguard iniciado con perfil Config"
        else
            log_message "Error al iniciar Wireguard con perfil Config"
        fi
        ;;
    "Config")
        log_message "Deteniendo Wireguard con perfil Config"
        /bin/sh /usr/lib/wireguard/stopvpn.sh Config
        if [ $? -eq 0 ]; then
            sleep 10 # Esperar más tiempo para asegurar que Wireguard se detenga completamente
            log_message "Iniciando Wireguard con perfil Configvps"
            /bin/sh /usr/lib/wireguard/startvpn.sh Configvps
            if [ $? -eq 0 ]; then
                echo "Configvps" > $STATE_FILE
                log_message "Wireguard iniciado con perfil Configvps"
            else
                log_message "Error al iniciar Wireguard con perfil Configvps"
            fi
        else
            log_message "Error al detener Wireguard con perfil Config"
        fi
        ;;
    "Configvps")
        log_message "Deteniendo Wireguard con perfil Configvps"
        /bin/sh /usr/lib/wireguard/stopvpn.sh Configvps
        if [ $? -eq 0 ]; then
            sleep 10 # Esperar más tiempo para asegurar que Wireguard se detenga completamente
            log_message "Iniciando Wireguard con perfil Config"
            /bin/sh /usr/lib/wireguard/startvpn.sh Config
            if [ $? -eq 0 ]; then
                echo "Config" > $STATE_FILE
                log_message "Wireguard iniciado con perfil Config"
            else
                log_message "Error al iniciar Wireguard con perfil Config"
            fi
        else
            log_message "Error al detener Wireguard con perfil Configvps"
        fi
        ;;
esac
EOF
chmod +x /usr/lib/wireguard/wps_button.sh

cat << 'EOF' > /etc/rc.button/wps
#!/bin/sh

case "$ACTION" in
    pressed)
        /usr/lib/wireguard/wps_button.sh
        ;;
esac
EOF
chmod +x /etc/rc.button/wps
