#!/bin/sh

# Crear el script intermedio para gestionar el estado de Wireguard
cat << 'EOF' > /usr/lib/wireguard/wps_button.sh
#!/bin/sh

STATE_FILE="/tmp/wireguard_state"

if [ ! -f $STATE_FILE ]; then
    # Si el archivo de estado no existe, crear y asumir que Wireguard está detenido
    echo "stopped" > $STATE_FILE
fi

STATE=$(cat $STATE_FILE)

if [ "$STATE" = "stopped" ]; then
    # Iniciar Wireguard y actualizar el estado
    /bin/sh /usr/lib/wireguard/startvpn.sh Config
    echo "started" > $STATE_FILE
else
    # Detener Wireguard y actualizar el estado
    /bin/sh /usr/lib/wireguard/stopvpn.sh Config
    echo "stopped" > $STATE_FILE
fi
EOF

# Hacer que el script intermedio sea ejecutable
chmod +x /usr/lib/wireguard/wps_button.sh

# Configurar el archivo /etc/rc.button/wps para usar el nuevo script
cat << 'EOF' > /etc/rc.button/wps
#!/bin/sh

case "$ACTION" in
    pressed)
        /usr/lib/wireguard/wps_button.sh
        ;;
esac
EOF

# Hacer que el archivo /etc/rc.button/wps sea ejecutable
chmod +x /etc/rc.button/wps
echo "El router sera reiniciado..."
sleep 3

# Reiniciar el router para aplicar los cambios
reboot
