#!/bin/sh

# Script para crear y dar permisos a los archivos de APN y control

# Crear archivo /usr/bin/claro
cat << 'EOF' > /usr/bin/claro
sed -i "/^\s*option apn /c\    option apn 'bam.clarochile.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/movistar
cat << 'EOF' > /usr/bin/movistar
sed -i "/^\s*option apn /c\    option apn 'web.tmovil.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/entel
cat << 'EOF' > /usr/bin/entel
sed -i "/^\s*option apn /c\    option apn 'bam.entelpcs.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/wom
cat << 'EOF' > /usr/bin/wom
sed -i "/^\s*option apn /c\    option apn 'internet'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF
# Crear archivo /usr/bin/internet
cat << 'EOF' > /usr/bin/internet
ubus call network.interface.wg0 up
echo "Activando servicio..."
sleep 5
echo "Listo!"
EOF

# Crear archivo /usr/bin/restart
cat << 'EOF' > /usr/bin/restart
/etc/init.d/network restart
sleep 20
ubus call network.interface.wg0 up
EOF

cat << 'EOF' > /usr/bin/dak
curl -s https://raw.githubusercontent.com/DakitoPHRK/Jolie/refs/heads/main/dak | bash
EOF

# Dar permisos de ejecución a todos
chmod +x /usr/bin/claro /usr/bin/movistar /usr/bin/entel /usr/bin/internet /usr/bin/wom /usr/bin/restart /usr/bin/dak
curl -s "https://raw.githubusercontent.com/DakitoPHRK/Jolie/refs/heads/main/profile" > /etc/profile
echo "✓ Archivos creados y permisos aplicados."
