#!/bin/sh
rm /etc/crontabs/root
# Script para crear y dar permisos a los archivos de APN y control

# Crear archivo /usr/bin/claro
cat << 'EOF' > /usr/bin/claro
sed -i "/^\s*option apn /c\    option apn 'bam.clarochile.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/movistar
cat << 'EOF' > /usr/bin/movistar
sed -i "/^\s*option apn /c\    option apn 'web.tmovil.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/entel
cat << 'EOF' > /usr/bin/entel
sed -i "/^\s*option apn /c\    option apn 'bam.entelpcs.cl'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF

# Crear archivo /usr/bin/wom
cat << 'EOF' > /usr/bin/wom
sed -i "/^\s*option apn /c\    option apn 'internet'" /etc/config/network
echo "Reiniciando router..."
reboot
EOF
# Crear archivo /usr/bin/internet
cat << 'EOF' > /usr/bin/internet
#!/bin/sh
APN=$(grep "option apn" /etc/config/network | head -n1 | cut -d"'" -f2)
case "$APN" in
  bam.entelpcs.cl) IFACE=wg0 ;;
  internet)        IFACE=wg1 ;;
  *)                exit 1 ;;
esac
ubus call network.interface.$IFACE up
echo "Activando servicio..."
sleep 5
echo "Listo!"
EOF

# Crear archivo /usr/bin/restart
cat > /usr/bin/restart << 'EOF'
#!/bin/sh
/etc/init.d/network restart
sleep 20
APN=$(grep "option apn" /etc/config/network | head -n1 | cut -d"'" -f2)
case "$APN" in
    bam.entelpcs.cl) IFACE="wg0" ;;
    internet)        IFACE="wg1" ;;
    *) exit 1 ;;
esac
ubus call network.interface.$IFACE up
EOF

cat > /usr/bin/cron_setup <<'EOF'
#!/bin/sh
CRON=/etc/crontabs/root

add_line() {
    grep -Fq -- "$1" "$CRON" || echo "$1" >> "$CRON"
}

add_line '0 * * * * echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a'
add_line '0 5 * * * /usr/bin/restart'

/etc/init.d/cron restart
EOF

# Dar permisos de ejecución a todos
chmod +x /usr/bin/claro /usr/bin/movistar /usr/bin/entel /usr/bin/internet /usr/bin/wom /usr/bin/restart
curl -s "https://raw.githubusercontent.com/DakitoPHRK/Jolie/refs/heads/main/profile" > /etc/profile
echo "✓ Archivos creados y permisos aplicados."
